# Generated by Django 4.2.7 on 2024-06-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_person_remove_user_login_remove_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
