version: "3.3"
networks:
  backend:
    driver: bridge
services:
  app:
    container_name: backend
    env_file: ./backend/.env
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - postgress
  postgress:
    container_name: postgres_db
    image: postgres
    env_file: ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: umbrellamixmail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: terrarik22
    ports:
      - 5433:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgress
volumes:
  postgres-data:
  pgadmin:
