# Generated by Django 4.2.7 on 2024-09-07 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
