# Generated by Django 4.2.7 on 2024-09-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarlabshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
