# Generated by Django 4.2.7 on 2024-09-16 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('solarlabshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('parentid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
