# Generated by Django 4.2.7 on 2024-10-07 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('solarlabshop', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
