# Generated by Django 4.2.7 on 2024-09-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarlabshop', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
