# Generated by Django 4.2.7 on 2024-10-07 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('solarlabshop', '0003_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
