# Generated by Django 4.2.7 on 2024-06-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0003_delete_person_remove_user_login_remove_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
